### ISSUE TITLE
(Для голосующего) изменение функционала кнопок weekslider

### ISSUE THREAD

**Issue by 6ocra3** [atmosferum/frontend#18]
Сейчас стрелочки - переход на следующую неделю, будет лучше если стрелочки - переход на неделю со следующим интервалом.

**Comment by fedor-resh** [comment]
Сейчас календарь по ссылке к ивенту (для голосующих) открывается на текущей недели, надо переделать так чтобы он открывался на недели с самым ранним интервалом админа

**Comment by fedor-resh** [comment]
меняем перескакивание к следующему интервалу на подсвечивание того есть ли справа или  слева интервал
